### ISSUE TITLE
Monterey

### ISSUE THREAD

**Issue by ejh4286** [stackia/hackintosh-rog-strix-trx40#1]
I have this same board.  I’ve upgradec open core to 0.7.5 and its boots to big sur no problem.  But it absolutely wont upgrade to monterey.  Have you had any success?

**Comment by stackia** [comment]
Sorry but I no longer use hackinosh for work now. It's so annoying to upgrade macOS when using hackintosh and finally I decided to move to a genuine Apple Mac for daily uses.

**Comment by ejh4286** [comment]
I understand.  Thanks anyway.
